#!/usr/bin/env sh

# Application Launches

# Terminal
alt - q : open -na /System/Applications/Utilities/Terminal.app

# Browser
alt - b : open -a /Applications/Firefox.app

# Code Editor
alt - c : open -na /Applications/Visual\ Studio\ Code.app

# Window Management

# Navigation - focus window
alt - left : yabai -m window --focus west
alt - down : yabai -m window --focus south
alt - up : yabai -m window --focus north
alt - right : yabai -m window --focus east

# Moving windows
shift + alt - left : yabai -m window --swap west
shift + alt - down : yabai -m window --swap south
shift + alt - up : yabai -m window --swap north
shift + alt - right : yabai -m window --swap east

# Move focus container to workspace
shift + alt - 1 : yabai -m window --space 1; yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space 2; yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space 3; yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space 4; yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space 5; yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space 6; yabai -m space --focus 6

# Resize windows
ctrl + alt - left : yabai -m window --resize left:-50:0; \
                    yabai -m window --resize right:-50:0
ctrl + alt - down : yabai -m window --resize bottom:0:50; \
                    yabai -m window --resize top:0:50
ctrl + alt - up : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
ctrl + alt - right : yabai -m window --resize right:50:0; \
                     yabai -m window --resize left:50:0

# Float / Unfloat window
shift + alt - space : yabai -m window --toggle float; \
                      yabai -m window --grid 4:4:1:1:2:2

# Make window fullscreen
alt - f : yabai -m window --toggle zoom-fullscreen

# Toggle split orientation
alt - o : yabai -m window --toggle split

# Rotate windows clockwise and anticlockwise
ctrl + alt - r : yabai -m space --rotate 270
ctrl + alt + shift - r : yabai -m space --rotate 90

# Balance out all windows
ctrl + alt - b : yabai -m space --balance

# Change layout (using ctrl + alt + number keys)
ctrl + alt - 1 : yabai -m space --layout bsp
ctrl + alt - 2 : yabai -m space --layout stack
ctrl + alt - 3 : yabai -m space --layout float

# Restart yabai
ctrl + alt + shift - 0 : yabai --restart-service
